### ISSUE TITLE
Compile task list for Django 1.11 upgrade

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#3142]
- Incorporate the dependency compatibility analysis from Urban Apps (Cicero)
- Research all dependencies for compatibility
- Include removing pending edits as a task
- Review deprecation notes from Django 1.9, 1.10, and 1.11

**Comment by maurizi** [comment]
Dependencies that will/may need to be updated:
- [ ] `django-apptemplates` - supports 1.10, unclear if it does or doesn't support 1.11
- [ ] `django-contrib-comments` - we're on version 1.7.3, 1.8 supports Django 1.11. No breaking changes.
- [ ] `django-hstore` - Doesn't support Django 1.10+ and is currently unmaintained. We switched away from using it in https://github.com/OpenTreeMap/otm-core/pull/3124 but it is still in our `requirements.txt` and is referenced from a migration. _Do we need to squash migrations to update?_
- [ ] `django-js-reverse` - supports 1.10, unclear if it does or doesn't support 1.11
- [ ] `django-queryset-csv` - supports 1.10, unclear if it does or doesn't support 1.11
- [ ] `django-redis` - we're on version 4.4.4, 4.8.0 is the latest and appears to support Django 1.11. No listed breaking changes.
- [ ] We're currently using `django-registration-redux` 1.4. [There seems to be support for Django 1.11](https://travis-ci.org/macropin/django-registration/builds/225810787) in the latest release (1.6), but there are [**breaking changes**](https://github.com/macropin/django-registration/blob/master/CHANGELOG#L23-L27)
- [ ] `django-statsd-mozilla` - No Django 1.9+ support (!!!). Upcoming 0.4 release should 1.11+ support  once it is released (https://github.com/django-statsd/django-statsd/issues/97)
- [ ] `django-storages` - we're using version 1.5. There is support for Django 1.11 in the latest release (1.6), but there are [**breaking changes**](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#16-2017-06-21)
- [ ] `django-threadedcomments` - supports 1.10, unclear if it does or doesn't support 1.11
- [ ] `django-url-tools` - doesn't support Django 1.9+, currently unmaintained.
- [ ] [`django-tinsel` has changes awaiting review to support 1.10+](https://github.com/azavea/django-tinsel/pull/6)
- [ ] `django-webpack-loader` - we're on 0.3.3, curent version (0.5) lists support for Django 1.11
- [ ] `rollbar` - master branch has an unreleased commit fixing a _deprecation_ warning for Django 1.10. Unclear if we need to upgrade, but probably a good idea regardless

**Comment by maurizi** [comment]
Code changes we'll need to make:

Django 1.8 deprecations:
 - template settings have changed to support Jinja2 as a built-in templater, and we'll need to migrate to the new settings names. (everything is now nested under `TEMPLATES`)
 - `option_list` is deprecated in management commands, so we'll need to update all of our built-in management commands
 - `GeoQuerySet` aggregate methods have been replaced with standalone functions that work with `aggregate(...)`, and `GeoManager` in general is deprecated in favor of stand-alone functions & `__fn=...` lookups

Django 1.9 deprecations/removals/changes:
 - There are now built-in password validators we may want to consider using
 - We may want to switch our test scripts to use parallel tests
 - `AbstractBaseUser` moved locations, so we'll need to update our `AbstractUniqueEmailUser` subclass
 - The PostGIS DB backend was renamed
 - `compilemessages` & `makemessages` now automatically work on all Django apps, so we should update docs/scripts for i18n
 - `Paginator.page_range` now returns an iterator instead of a list, which will likely require updating the custom templatetag we use with Paginators
 - `RequestSite` and `get_current_site` have been moved
 - `request.REQUEST` (which was deprecated for several versions) has been removed.

Django 1.10 deprecations/removals/changes:
 - There is now built-in full text search / fuzzy string matching support, so we may want to switch to that in the importer
 - CSRF tokens now changes on every request, we _may_ need to handle this when making AJAX requests for HTML partials
 - `get_prep_lookup` & `get_db_prep_lookup` (used by our internal `JSONField`) methods have been removed in favor of custom lookup classes. We'll need to switch to those (or switch to the new built-in `JSONField`)
 - subclasses of `AbstractBaseUser` are now required to call `super()` in their `clean()` methods.
 - `model_to_dict`, used by our `Dictable` mixin now handles `ManyToMany` fields differently and will need to be tested
 - `User.is_authenticated` & `User.is_anonymous` are now properties instead of methods

Django 1.10 deprecations/removals/changes:
 - `Template.render` no longer supports `Context` or `RequestContext` as a parameter, only `dict` is supported.
 - We'll need to check for thread-safety in our custom template tags, or disable `cached_template_loader`
